# Generated by Django 4.0.3 on 2024-11-29 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trigger_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$ROlTdBHOPtP4tfuLqHDokA$MiZPsW0G6ppr7DXHX49x62A6V6IBhnh0egAWcxJaTfM=', max_length=128),
        ),
    ]
